/* Slangify Core 30, corpus v1. Original examples and paraphrased explanations.
   Dictionary meanings checked 2026-09-13. Context judgements are teaching guidance,
   not quotations from the dictionaries. Kazakh text needs teacher review before a study. */
(function(root){
  const rows = [
    ['gonna','Spoken form','Going to do something.','Бір нәрсені істемек болу.','going to','I am gonna bring my notebook.','A voice message to a friend about tomorrow.','A formal written application.','Use “going to” before a verb in formal writing.'],
    ['wanna','Spoken form','Want to do something.','Бір нәрсені істегісі келу.','want to','I wanna learn another phrase.','Asking a friend to join a drawing session.','A formal email requesting a school place.','Here “wanna” means “want to”, followed by a verb.'],
    ['gotta','Spoken form','Have to do something.','Бір нәрсені істеу керек.','have to','I gotta finish this chapter.','Telling a friend why you need to leave.','A formal statement about your responsibilities.','Use “have to” or “must” for a clear formal statement.'],
    ['kinda','Spoken form','To a small degree.','Біраз; сәл.','somewhat','This puzzle is kinda tricky.','Sharing a casual opinion about a puzzle.','A scientific report that requires precise wording.','“Kinda” is the casual spelling of “kind of”; here it means “somewhat”.'],
    ['dunno','Spoken form','Do not know the answer.','Жауабын білмеу.','do not know','I dunno which bus we need.','Replying casually to a close friend.','A formal reply to an interviewer.','“I do not know yet” sounds clearer and more considered in an interview.'],
    ['yeah','Informal word','A casual way to agree.','Иә; келісуді білдіреді.','yes','Yeah, we can study together.','Agreeing to a plan with a friend.','A written form that asks for “yes” or “no”.','“Yeah” is normal in casual speech; use the requested answer on a form.'],
    ['nope','Informal word','A casual negative answer.','Жоқ деген бейресми жауап.','no','Nope, that is not my pencil.','Answering a simple question from a friend.','A formal email declining an invitation from a school.','A short “nope” can sound dismissive; a polite full sentence works better.'],
    ['bro','Slang','A casual address for a male friend.','Досқа айтылатын бейресми қаратпа сөз.','friend','Thanks for the notes, bro.','Thanking a friend who likes being called bro.','Addressing an unfamiliar interviewer.','Use a name or title when you do not know how someone likes to be addressed.'],
    ['buddy','Informal word','A friend or companion.','Дос; жолдас.','companion','My buddy helped me carry the books.','Telling friends about someone you spend time with.','Addressing an unfamiliar school principal as “buddy”.','“Buddy” can be friendly between peers but too familiar with a stranger.'],
    ['chill','Informal word','Relax and take things easy.','Демалу; босаңсу.','relax','Let us chill after the lesson.','Suggesting a quiet break to a friend.','Telling an upset stranger “just chill” instead of listening.','As a command, “chill” may sound dismissive. Here we practise the verb meaning relax.'],
    ['LOL','Text abbreviation','Shows that you find something funny.','Бір нәрсенің күлкілі екенін білдіреді.','that is funny','LOL, the cat sat on my homework.','Reacting to a harmless joke in a friendly chat.','Responding to someone sharing a serious problem.','Read the mood first: a laughing response can seem unkind during a serious conversation.'],
    ['OMG','Text abbreviation','Shows surprise or excitement.','Таңғалу не қуанышты білдіреді.','that is surprising','OMG, our poster won first place!','Reacting to exciting news in a friends’ chat.','Opening a formal request to a school director.','The expansion is “oh my God”; a neutral reaction is “that is surprising”.'],
    ['BRB','Text abbreviation','You will return to the chat soon.','Чатқа жақында қайта ораласың.','I will be right back','BRB, I need my charger.','Briefly stepping away from an online group chat.','A formal letter to someone who may not know chat abbreviations.','BRB means “be right back”; it describes a short absence, not a goodbye for the day.'],
    ['BTW','Text abbreviation','Adds a side point or new topic.','Қосымша ой не жаңа тақырып қосады.','by the way','BTW, the library opens at nine.','Adding useful information in a casual message.','An academic essay requiring fully written transitions.','Use a full transition in formal prose; “BTW” is a messaging shortcut.'],
    ['FYI','Abbreviation','Introduces information for the reader.','Оқырманға қосымша ақпарат береді.','for your information','FYI, the meeting room has changed.','A brief update in a team chat where everyone knows the abbreviation.','Instructions for a beginner who does not understand abbreviations.','FYI also occurs at work. Audience and tone matter more than a blanket ban on abbreviations.'],
    ['ASAP','Abbreviation','As quickly as reasonably possible.','Мүмкіндігінше тезірек.','as soon as possible','Please send the slides ASAP.','A team message about a genuinely urgent shared task.','A non-urgent favour where you want to avoid sounding demanding.','ASAP can sound urgent. A polite request with a clear deadline is often more helpful.'],
    ['IMO','Text abbreviation','Marks your personal opinion.','Өз пікіріңді білдіреді.','in my opinion','IMO, the blue cover looks better.','Giving an opinion in a friendly design chat.','A formal essay that requires words to be written in full.','An opinion is not a fact; in formal writing, spell the phrase out and support your point.'],
    ['TBH','Text abbreviation','Introduces a frank opinion.','Шынын айтқанда.','to be honest','TBH, I prefer studying in the morning.','Politely sharing a preference in a friends’ chat.','A formal scholarship application using full sentences.','TBH means “to be honest”. Honesty still needs a respectful tone.'],
    ['IRL','Text abbreviation','Outside the online setting.','Интернеттен тыс, шынайы өмірде.','in real life','Our class finally met IRL.','Contrasting an online lesson with an in-person class in chat.','A formal notice for readers unfamiliar with online shortcuts.','Use “in person” or “in real life” when the abbreviation may be unclear.'],
    ['DIY','Abbreviation','Making something yourself.','Бір нәрсені өз қолыңмен жасау.','do it yourself','This is a DIY paper bookmark.','A craft-club poster for students familiar with DIY.','Instructions for a beginner who asks for every abbreviation to be explained.','DIY is also used outside slang. Explain it when your reader does not know it.'],
    ['hang out','Informal phrase','Spend relaxed time together.','Бірге еркін уақыт өткізу.','spend time together','We hang out near the library after class.','Inviting friends to spend time together.','A formal invitation to an academic interview.','Use “meet” or “spend time together” when a more neutral tone is needed.'],
    ['catch up','Conversational phrase','Learn or exchange the latest news.','Соңғы жаңалықтарды білісу.','exchange recent news','Let us catch up during the break.','Inviting a classmate to share news after a holiday.','Directions for a learner who understands only literal meanings.','“Catch up” has several meanings; here we focus on exchanging news. It can also be used at work.'],
    ['FOMO','Informal abbreviation','Worry about missing others’ experiences.','Басқалар қатысқан қызықтан қалып қоюдан алаңдау.','fear of missing out','I felt FOMO when I missed the class picnic.','Describing a feeling to a friend who knows the term.','An unexplained label in a report for readers new to the topic.','FOMO names a feeling. In formal discussion, define the term first.'],
    ['TIL','Text abbreviation','Introduces something you learned today.','Бүгін білген жаңалығыңды білдіреді.','today I learned','TIL that octopuses have three hearts.','Sharing a new fact in a class chat.','The opening of a formal science essay requiring full prose.','Write the full idea and give a source in a formal essay.'],
    ['cool','Informal word','Good or appealing.','Жақсы; ұнамды; керемет.','appealing','That is a cool notebook design.','Complimenting a friend’s design.','A formal lab report requiring a precise description.','Here “cool” expresses approval, not temperature. Explain what works in formal evaluation.'],
    ['awesome','Informal word','Extremely good or impressive.','Өте керемет; әсерлі.','impressive','Your class presentation was awesome.','Encouraging a classmate after a presentation.','A scientific conclusion requiring measured evidence.','Enthusiastic praise suits conversation; research needs specific evidence.'],
    ['lowkey','Slang','Somewhat, without making a big point of it.','Сәл; ашық білдірмей.','to some extent','I lowkey enjoy organizing my notes.','Admitting a small preference in a casual chat.','A formal survey response requiring precise language.','Also written “low-key”. Here we practise the informal adverb, not the adjective for something restrained.'],
    ['sus','Slang','Seems suspicious or doubtful.','Күмәнді; күдік тудырады.','suspicious','That strange game clue looks sus.','Discussing a fictional clue with teammates in a game.','A formal complaint where specific facts are required.','In a serious report, describe the evidence instead of relying on a slang label.'],
    ['GOAT','Slang abbreviation','Someone considered the best ever.','Барлық уақыттағы ең үздік деп саналатын адам.','greatest of all time','Our captain is the GOAT in our group chat.','Playfully praising a player in a friendly sports discussion.','A research ranking that needs stated criteria and evidence.','GOAT is often enthusiastic opinion. It does not prove an objective ranking.'],
    ['DM','Abbreviation','A private message on an online platform.','Онлайн платформадағы жеке хабарлама.','direct message','I sent my classmate a DM about the project.','Discussing a platform feature with classmates who use it.','A guide for a new user without first explaining the abbreviation.','DM can be a noun or a verb. Here the example uses the noun.']
  ];
  const words=rows.map((r,i)=>({id:'c'+String(i+1).padStart(2,'0'),word:r[0],kind:r[1],en:r[2],kk:r[3],neutral:r[4],example:r[5],good:r[6],bad:r[7],note:r[8],source:'https://www.merriam-webster.com/dictionary/'+encodeURIComponent(r[0]==='lowkey'?'low-key':r[0])}));
  words.find(x=>x.word==='BRB').source='https://dictionary.cambridge.org/us/dictionary/english/brb';
  words.find(x=>x.word==='TIL').source='https://dictionary.cambridge.org/dictionary/english/til';
  words.find(x=>x.word==='TBH').source='https://www.merriam-webster.com/wordplay/tbh-to-be-honest-the-meaning-is-perfectly-clear';
  const data={version:'core30-v1',checked:'2026-09-13',words};
  if(typeof module!=='undefined')module.exports=data;else root.SlangCourse=data;
})(typeof window!=='undefined'?window:globalThis);
